---
- hosts: all # part running on all hosts
  become: true

  tasks:
    #  - debug:
    #  msg:
    #  - "{{ user }}"
    #  - "{{ group }}"

  - name: Install epel-release
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - epel-release

  - name: Install packages 
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - tcpdump

- hosts: inetRouter centralRouter 
  become: true
  roles:
    - router-role

- hosts: testClient1 testClient2 testServer1 testServer2
  become: true
  roles:
    - isolated-role
     
