---
- hosts: all # part running on all hosts
  become: true
  tasks:

  - name: Install epel-release # переведём синтаксис yum из deprecated
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - epel-release

- name: Setup zabbix
  hosts: zabbixsrv
  become: yes
  roles:
    - zabbix-role
