---
- name:  Configure host lab10
  hosts: lab10
  become: yes
  vars:
    epel: epel-release
    packages: 
      - spawn-fcgi
      - php
      - php-cli
      - mod_fcgid
      - httpd
    unit_files_dst_path: /etc/systemd/system/
    httpd_conf_path:  /etc/httpd/conf/
    sysconfig_path: /etc/sysconfig/
    
  tasks:
    - name: Install EPEL Repo package
      yum:
        name: "{{ epel }}"
        state: present
      tags:
        - epel-installation

    - name: Install requied packages
      yum:
        name: "{{ packages }}"
        state: present
      tags:
        - install-packages

    - name: Copy files for configure services
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: 'files/watchlog.conf', dest: '/etc/sysconfig', mode: '0644' }
        - { src: 'files/watchlog.log', dest: '/var/log', mode: '0644' }
        - { src: 'files/watchlog.sh', dest: '/opt', mode: '0744' }
        - { src: 'files/watchlog.timer', dest: '{{ unit_files_dst_path }}', mode: '0644' }
        - { src: 'files/watchlog.service', dest: '{{ unit_files_dst_path }}', mode: '0644' }
        - { src: 'files/httpd@.service', dest: '{{ unit_files_dst_path }}', mode: '0644' }
        - { src: 'files/first.conf', dest: '{{ httpd_conf_path }}', mode: '0644' }
        - { src: 'files/second.conf', dest: '{{ httpd_conf_path }}', mode: '0644' }
        - { src: 'files/httpd-first', dest: '{{ sysconfig_path }}', mode: '0644' }
        - { src: 'files/httpd-second', dest: '{{ sysconfig_path }}', mode: '0644' }

    - name: Start units
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
        daemon_reload: yes
      with_items:
        - watchlog.timer
        - watchlog.service
        - httpd@first
        - httpd@second
