---
# tasks file for provision/roles/backup-server-role

- name: Check directory exists
  ansible.builtin.stat:
    path: /var/backup
  register: var_backup_exists


- name: Create partition, filesystem and mount point
  shell: |
    echo -e "o\nn\np\n1\n\n\nw" | fdisk /dev/sdb
    mkfs.xfs /dev/sdb1
    mkdir /var/backup
    mount /dev/sdb1 /var//backup/
  args:
    warn: no
  when: var_backup_exists.stat.exists == False
