version: "3"

services:
  nginx:
    image: deron73/my-nginx-image:0.1
    container_name: nginx
    depends_on: 
        - phpfpm
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front_end
      
  phpfpm:
    container_name: phpfpm
    image: deron73/my-php-fpm-image:0.1
    volumes:
      - ./www:/var/www/html
    ports:
      - 9000:9000
    networks:
      - front_end

networks:
  front_end:
