# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :ldapsrv => {
        :hostname => "ldapsrv.otus.lab",
        :box_name => "centos/7",
        :net => [
                 { ip: '192.168.11.150', virtualbox__intnet: 'ldap' }
                ],
        # VM CPU count
        :cpus => 2,
        # VM RAM size (Mb)
        :memory => 4096 
  },
  :client => {
        :hostname => "client.otus.lan",
        :box_name => "centos/7",
       	:net =>	[
       	         { ip: '192.168.11.10', virtualbox__intnet: 'ldap' }
       	        ],
        # VM CPU count
        :cpus => 1,
        # VM RAM size (Mb)
        :memory => 512
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    # Disable synced folder
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxconfig[:hostname]

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        case boxname.to_s
          when "ldapsrv" 
            box.vm.network :forwarded_port, guest: 80, host: 80
            box.vm.network :forwarded_port, guest: 443, host: 443 
        end

        box.vm.provider "virtualbox" do |v|
          # Set VM RAM size and CPU count
          v.memory = boxconfig[:memory]
          v.cpus = boxconfig[:cpus]
        end

        box.vm.provision "shell", inline: <<-SHELL
          timedatectl set-timezone Europe/Moscow
	  mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL

#        case boxname.to_s
#          when "client"
#            box.vm.provision "ansible" do |ansible|
#           ansible.verbose = "vv"
#            ansible.playbook = "./playbook.yml"
#            ansible.become = "true"
#            ansible.limit = "all"
#          end
#        end

      end
  end
end
