# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "shell", inline: <<-SHELL
      timedatectl set-timezone Europe/Moscow
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
  SHELL

  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vv"
    ansible.playbook = "provision/playbook.yml"
    #ansible.sudo = "true"
    ansible.become = "true" 
  end

  config.vm.provider "virtualbox" do |v|
	  v.memory = 2048
  end

  config.vm.define "ipaserver" do |ipaserver|
    ns01.vm.network "private_network", ip: "192.168.50.200", virtualbox__intnet: "ldap"
    ns01.vm.hostname = "ipaserver"
  end

  config.vm.define "client" do |client|
    ns02.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "ldap"
    ns02.vm.hostname = "client"
  end

end
