# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "shell", inline: <<-SHELL
      timedatectl set-timezone Europe/Moscow
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
  SHELL

#  config.vm.provision "ansible" do |ansible|
#     ansible.verbose = "vv"
#    ansible.playbook = "provision/playbook.yml"
#    ansible.become = "true" 
#  end

  config.vm.provider "virtualbox" do |v|
	  v.memory = 2048
  end

  config.vm.define "ipa" do |ipa|
    ipa.vm.network "private_network", ip: "192.168.50.200", virtualbox__intnet: "ldap"
    ipa.vm.hostname = "ipa"
  end

  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "ldap"
    client.vm.hostname = "client"
  end

end
