---
# tasks file for provision/percona-install
#
- name: Install percona repository
  yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present

- name: Install Percona server and MySQL-python module
  yum:
    name: 
      - Percona-Server-server-57
      - MySQL-python
    state: present

- name: "[RedHat] Ensure Percona XtraBackup is installed"
  yum:
    name:
      - "{{ xtrabackup_package_name }}"
      - libgcrypt
      - openssl
      - qpress
    update_cache: true

- name: Start MySQL
  systemd:
    name: mysql
    state: started
    enabled: yes

- name: Get automate generated mysql password
  shell: grep 'A temporary password is generated' /var/log/mysqld.log | awk '{print $11}' 
  register: current_password
      
- debug:
    msg:
    - "{{ current_password.stdout }}"
    - "{{ mysql_password }}"

- name: Set mysql password
  shell: 
    mysql --connect-expired-password -uroot -p'{{ current_password.stdout }}' -e 'ALTER USER USER() IDENTIFIED BY "{{ mysql_password }}"'
  ignore_errors: yes

#'

- name: Copy my.cnf
  template:
    src: templates/my.cnf.j2
    dest: /root/.my.cnf
    mode: 0600

