---
# tasks file for provision/srv1cv83_setup

- name: Config 1540-1541 port firewalld
  firewalld:
    port: 1540-1541/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Config 1560-1590 port firewalld
  firewalld:
    port: 1560-1590/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Prepare 1c unit
  template:
    src: srv1cv83.service.j2
    dest: /etc/systemd/system/srv1cv83.service
    owner: root
    group: root
  tags:
    - 1c_unit

- name: Start srv1cv83 systemd unit
  systemd:
    name: srv1cv83.service
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - 1c_start

- name: Start ras daemon cluster
  become_user: usr1cv8
  shell: | 
    /opt/1C/v8.3/x86_64/ras --daemon cluster
    sleep 60

- name: Get 1c cluster list
  become_user: usr1cv8
  shell: /opt/1C/v8.3/x86_64/rac cluster list | grep 'cluster' | awk '{ print $3 }'
  register: cluster_name

  #- debug:
  #  msg:
  #  - "{{ cluster_name.stdout }}"

- name: Create 1C database
  become_user: usr1cv8
  shell: /opt/1C/v8.3/x86_64/rac infobase --cluster={{ cluster_name.stdout }} create --create-database --name={{ database_1c }}  --dbms=PostgreSQL --db-server={{ db_server }} --db-name={{ database_1c }} --locale=ru --db-user={{ db_user }} --db-pwd={{ db_pwd }} --license-distribution=allow
  ignore_errors: yes

- name: Copy hasp files
  copy:
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'install_hasp_centos78.sh', dest: '/home/vagrant/', mode: '0700' } 
    - { src: '50user.json', dest: '/etc/usbhaspkey/', mode: '0644' } 
    - { src: 'usbhaspemul.service', dest: '/etc/systemd/system/', mode: '0644' } 

- name: Check usbhaspemul status
  command: systemctl status usbhaspemul.service
  register: usbhaspemul_status
  ignore_errors: yes

  #- debug:
  #    msg:
  #      - "{{ usbhaspemul_status.rc }}"

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  when: usbhaspemul_status.rc != 0

- name: Reboot a slow machine that might have lots of updates to apply
  reboot:
    reboot_timeout: 60
  when: usbhaspemul_status.rc != 0

- name: Run usbhasp install script
  shell: /home/vagrant/install_hasp_centos78.sh
  ignore_errors: yes
  when: usbhaspemul_status.rc != 0

- name: Start usbhaspemul unit
  systemd:
    name: usbhaspemul
    state: started
    enabled: yes
    daemon_reload: yes
    
