---
# tasks file for provision/srv1cv83_setup

- name: Config 1540-1541 port firewalld
  firewalld:
    port: 1540-1541/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Config 1560-1590 port firewalld
  firewalld:
    port: 1560-1590/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Install list of necessary for 1c packages
  yum:
    name: "{{ packages_for1c }}"
    state: latest

- name: Get stats of the srv1cv8 install directory
  stat:
    path: "{{ app1c_directory }}"
  register: path_1c

- name: Copy app from remote server and unarchive
  unarchive:
    src: files/rpm64_8_3_16_1814.tar.gz
    dest: /tmp/
    owner: vagrant
    group: vagrant
    mode: '0644' 

- debug:
    msg:
    - "{{ app1c_packages }}"
  tags:
    - 1c_vars

- name: Install list of 1c packages
  yum:
    name: "/tmp/{{ item }}"
    state: present 
    disable_gpg_check: yes
  loop: "{{ app1c_packages }}"
  tags:
    - 1c_rpm

- name: Prepare 1c unit
  template:
    src: srv1cv83.service.j2
    dest: /etc/systemd/system/srv1cv83.service
    owner: root
    group: root
  tags:
    - 1c_unit

- name: Start srv1cv83 systemd unit
  systemd:
    name: srv1cv83.service
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - 1c_start

- name: Start ras daemon cluster
  become_user: usr1cv8
  shell: | 
    /opt/1C/v8.3/x86_64/ras --daemon cluster
    sleep 60

- name: Get 1c cluster list
  become_user: usr1cv8
  shell: /opt/1C/v8.3/x86_64/rac cluster list | grep 'cluster' | awk '{ print $3 }'
  register: cluster_name

- debug:
    msg:
    - "{{ cluster_name.stdout }}"

- name: Create 1C database
  become_user: usr1cv8
  shell: /opt/1C/v8.3/x86_64/rac infobase --cluster={{ cluster_name.stdout }} create --create-database --name={{ database_1c }}  --dbms=PostgreSQL --db-server={{ db_server }} --db-name={{ database_1c }} --locale=ru --db-user={{ db_user }} --db-pwd={{ db_pwd }} --license-distribution=allow
  ignore_errors: yes
