---
gw:
  - dev: eth1
    nh: 192.168.255.254

filebeat_modules:
  - system
  - nginx

sysctl_params:
  - parameter: net.ipv4.ip_forward
    value: '1'
  - parameter: net.ipv4.conf.all.forwarding
    value: '1'
  - parameter: net.ipv4.conf.all.rp_filter
    value: '2'
