---
# tasks file for provision/1cv83_install

- name: Install list of necessary for 1c packages
  yum:
    name: "{{ packages_for1c }}"
    state: latest

    #- name: Get stats of the srv1cv8 install directory
    #stat:
    #path: "{{ app1c_directory }}"
    #register: path_1c

- name: Copy app from remote server and unarchive
  unarchive:
    src: files/rpm64_8_3_16_1814.tar.gz
    dest: /tmp/
    owner: vagrant
    group: vagrant
    mode: '0644' 

    #- debug:
    #msg:
    #- "{{ app1c_packages }}"
    #tags:
    #- 1c_vars

- name: Install list of 1c packages
  yum:
    name: "/tmp/{{ item }}"
    state: present 
    disable_gpg_check: yes
  loop: "{{ app1c_packages }}"
  tags:
    - 1c_rpm

- name: Create directory /usr/share/fonts/truetype
  file:
    path: /usr/share/fonts/truetype/    
    state: directory
    owner: root
    group: root

- name: Copy ttf fonts from remote server and unarchive
  unarchive:
    src: files/msttcorefonts.zip
    dest: /usr/share/fonts/truetype/
    owner: root
    group: root
    mode: '0644' 

    #- debug:
    #msg:
    #- "{{ app1c_packages }}"
    #tags:
    #- 1c_vars

- name: Install MS ttf fonts
  command: fc-cache –fv
