call plug#begin('~/.vim/plugged')

" https://github.com/romainl/flattened
Plug 'romainl/flattened'

" https://github.com/itchyny/lightline.vim
Plug 'itchyny/lightline.vim'

" https://github.com/scrooloose/nerdtree
Plug 'scrooloose/nerdtree'

" https://vimawesome.com/plugin/syntastic
Plug 'vim-syntastic/syntastic'

Plug 'rainglow/vim'

Plug 'vim-airline/vim-airline'

Plug 'vim-airline/vim-airline-themes'

Plug 'morhetz/gruvbox'

call plug#end()

"colorscheme flattened-dark

"colorscheme kiwi

set number
"set linespace=1
"set guifont=Fira\ Code:h12
"set cursorline

"display lightline
set laststatus=2
set noshowmode

autocmd vimenter * NERDTree
map <F5> :NERDTreeToggle<CR>
autocmd vimenter * ++nested colorscheme gruvbox
set background=dark    " Setting dark mode

set mouse=a

let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled = 1
let g:molokai_original = 1
let g:rehash256 = 1

set splitbelow
terminal ++rows=10
