---
# handlers file for provision/router-role
- name: restart_chrony
  systemd:
    name: chronyd
    state: restarted

- name: reload_network_interface
  become: yes
  shell: 
    nmcli con reload

- name: restart_Network
  become: yes
  service:
    name: network
    state: restarted

- name: restart_NetworkManager
  become: yes
  systemd:
    name: NetworkManager
    state: restarted

- name: wait_for_new_network_settings
  local_action: 
    module: wait_for host={{ ansible_ssh_host | default(inventory_hostname) }} port="{{ ansible_port}}" delay=10 timeout=300

- name: start_quagga
  systemd:
    state: '{{ item.state }}'
    name: '{{ item.name }}'
    enabled: '{{ item.enabled }}'
    daemon_reload: yes
  with_items:
    - '{{ quagga_services }}' 

- name: restart_quagga
  systemd:
    name: '{{ item.name }}'
    enabled: '{{ item.enabled }}'
    state: restarted
  with_items:
    - '{{ quagga_services }}' 

- name: reload_firewalld
  systemd:
    state: reloaded
    name: firewalld
