---
# tasks file for provision/nginx_setup
- name: Install packages for nginx_setup role
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ packages }}"

- name: Permit traffic in default zone for http service
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: Start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
