---
# tasks file for provision/nginx_setup
- name: Install packages for nginx_setup role
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ packages }}"

- name: Permit traffic in default zone for http service
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: Permit traffic in default zone for https service
  firewalld:
    service: https
    permanent: yes
    state: enabled
    immediate: yes

- name: Config nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Start 
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Remove default from eth0
  shell: nmcli connection modify System\ eth0 ipv4.never-default yes && nmcli connection up System\ eth0

- name: Setup default route
  shell: "nmcli connection modify System\\ {{ item.dev }} ipv4.gateway {{ item.nh }} && nmcli connection up System\\ {{ item.dev }}"
  with_items: 
    - "{{ gw }}"
