---
- name: Configure Prometheus + Node Exporter + Grafana
  hosts: all
  become: yes
  roles:
    - base_config
    - cloudalchemy.prometheus
    - cloudalchemy.node-exporter
    - cloudalchemy.grafana
  vars:
    prometheus_targets:
      node:
      - targets:
        - localhost:9100
        labels:
          env: lab15
