---
master_ip: 192.168.11.150
slave_ip: 192.168.11.151
backup_ip: 192.168.11.152
srv1c_ip: 192.168.11.102
postgresql_version: "11"
#postgresql_service: postgresql-11
postgresql_service: postgrespro-std-11.service
#postgresql_bin_path: "/usr/pgsql-11/bin"
postgresql_bin_path: "/opt/pgpro/std-11/bin/pg-setup"
#postgresql_data_dir: "/var/lib/pgsql/11/data"
postgresql_data_dir: "/var/lib/pgpro/std-11/data"
#postgresql_config_path: "/var/lib/pgsql/11/data"
postgresql_config_path: "/var/lib/pgpro/std-11/data"
physical_replication_slot: standby_slot
replica_username: replica
replica_password: Pass@Word@Rep
barman_username: barman
barman_password: Pass@Word@Bar
streaming_barman: streaming_barman
streaming_barman_password: Pass@Word@Str

lab_domain_name: otus.lab

nodes:
  - node: router
    node_ip: 192.168.11.254
    domain: "{{ lab_domain_name }}"
  - node: master
    node_ip: 192.168.11.150
    domain: "{{ lab_domain_name }}"
  - node: slave
    node_ip: 192.168.11.151
    domain: "{{ lab_domain_name }}"
  - node: backup
    node_ip: 192.168.11.152
    domain: "{{ lab_domain_name }}"
  - node: elk
    node_ip: 192.168.11.153
    domain: "{{ lab_domain_name }}"
  - node: zabbix
    node_ip: 192.168.11.154
    domain: "{{ lab_domain_name }}"
  - node: nginx
    node_ip: 192.168.11.100
    domain: "{{ lab_domain_name }}"
  - node: apache
    node_ip: 192.168.11.101
    domain: "{{ lab_domain_name }}"
  - node: srv1c
    node_ip: 192.168.11.102
    domain: "{{ lab_domain_name }}"
targets: 
  - master:9100
  - slave:9100
  - backup:9100
  - monlog:9100
