lab_domain_name: otus.lab

nodes:
  - node: router
    node_ip: 192.168.11.254
    domain: "{{ lab_domain_name }}"
  - node: master
    node_ip: 192.168.11.150
    domain: "{{ lab_domain_name }}"
  - node: slave
    node_ip: 192.168.11.151
    domain: "{{ lab_domain_name }}"
  - node: backup
    node_ip: 192.168.11.152
    domain: "{{ lab_domain_name }}"
  - node: elk
    node_ip: 192.168.11.153
    domain: "{{ lab_domain_name }}"
  - node: zabbix
    node_ip: 192.168.11.154
    domain: "{{ lab_domain_name }}"

targets: 
  - master:9100
  - slave:9100
  - backup:9100
  - monlog:9100
