---
archive_url: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65323039346233396635666436306665666365646230386232666462663662663934363037383832
          3039613765303462306238343935306664386161363266300a613032396565623032346261393633
          30653437363431653563333834623766653565396263653039663139333262616131343561353761
          6632336330643438610a373464363166343538336564346238653830613763666132343664326639
          37623063373032353935353438313165303039356438616634386139633266623864

#archive_url: files
remote_src_state: yes
master_ip: 192.168.11.150
slave_ip: 192.168.11.151
backup_ip: 192.168.11.152
srv1c_ip: 192.168.11.102
postgresql_version: "11"
#postgresql_service: postgresql-11
postgresql_service: postgrespro-std-11.service
#postgresql_bin_path: "/usr/pgsql-11/bin"
postgresql_bin_path: "/opt/pgpro/std-11/bin/pg-setup"
#postgresql_data_dir: "/var/lib/pgsql/11/data"
postgresql_data_dir: "/var/lib/pgpro/std-11/data"
#postgresql_config_path: "/var/lib/pgsql/11/data"
postgresql_config_path: "/var/lib/pgpro/std-11/data"
physical_replication_slot: standby_slot
replica_username: replica
replica_password: Pass@Word@Rep
barman_username: barman
barman_password: Pass@Word@Bar
streaming_barman: streaming_barman
streaming_barman_password: Pass@Word@Str
barman_stream_slot: master

lab_domain_name: otus.lab

nodes:
  - node: router
    node_ip: 192.168.11.254
    domain: "{{ lab_domain_name }}"
  - node: master
    node_ip: 192.168.11.150
    domain: "{{ lab_domain_name }}"
  - node: slave
    node_ip: 192.168.11.151
    domain: "{{ lab_domain_name }}"
  - node: backup
    node_ip: 192.168.11.152
    domain: "{{ lab_domain_name }}"
  - node: elkhost
    node_ip: 192.168.11.153
    domain: "{{ lab_domain_name }}"
  - node: zabbixhost
    node_ip: 192.168.11.154
    domain: "{{ lab_domain_name }}"
  - node: nginxhost
    node_ip: 192.168.11.100
    domain: "{{ lab_domain_name }}"
  - node: apachehost
    node_ip: 192.168.11.101
    domain: "{{ lab_domain_name }}"
  - node: srv1c
    node_ip: 192.168.11.102
    domain: "{{ lab_domain_name }}"
targets: 
  - master:9100
  - slave:9100
  - backup:9100
  - monlog:9100

sysctl_params:
  - parameter: vm.swappiness
    value: '10'
  - parameter: net.core.somaxconn
    value: '500'
  - parameter: net.core.netdev_max_backlog
    value: '500'

elkhost: elkhost.otus.lab

#server_address: "192.168.11.101"
#client_address: "192.168.11.102"
#client_hostname: client
#server_hostname: backupserver  
backup_user: backup
backup_group: backup
backup_home: /home/backup
backup_repo_path: /var/backup
backup_passphrase: 123456
backup_unit_files_dst_path: /etc/systemd/system/
backup_source: /etc
backup_client_hosts:
  - zabbixhost
  - master
  - slave
  - elkhost
  - nginxhost
  - apachehost
  - srv1c

