all:
  hosts:
    router:
      ansible_port: 2222
      ansible_private_key_file: .vagrant/machines/router/virtualbox/private_key
    master:
      ansible_port: 2200
      ansible_private_key_file: .vagrant/machines/master/virtualbox/private_key
    slave:
      ansible_port: 2201
      ansible_private_key_file: .vagrant/machines/slave/virtualbox/private_key
    backup:
      ansible_port: 2202
      ansible_private_key_file: .vagrant/machines/backup/virtualbox/private_key
    elkhost:
      ansible_port: 2203
      ansible_private_key_file: .vagrant/machines/elkhost/virtualbox/private_key
    zabbixhost:
      ansible_port: 2204
      ansible_private_key_file: .vagrant/machines/zabbixhost/virtualbox/private_key
    nginxhost:
      ansible_port: 2205
      ansible_private_key_file: .vagrant/machines/nginxhost/virtualbox/private_key
    apachehost:
      ansible_port: 2206
      ansible_private_key_file: .vagrant/machines/apachehost/virtualbox/private_key
    srv1c:
      ansible_port: 2207
      ansible_private_key_file: .vagrant/machines/srv1c/virtualbox/private_key
  vars:
    ansible_host: 127.0.0.1
    
