# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :router => {
        :hostname => "router.otus.lab",
        :box_name => "centos/7",
        # VM CPU count
        :cpus => 1,
        # VM RAM size (Mb)
        :memory => 256,
	:net => [
                 {ip: '192.168.11.254', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dmz-net"},
                ]
  },
#  :master => {
#        :hostname => "master.otus.lab",
#        :box_name => "centos/7",
#        # VM CPU count
#        :cpus => 2,
#        # VM RAM size (Mb)
#        :memory => 1024, 
#	:net => [
#                 {ip: '192.168.11.150', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dmz-net"},
#                ]
#  },
#  :slave => {
#        :hostname => "slave.otus.lab",
#        :box_name => "centos/7",
#        # VM CPU count
#        :cpus => 2,
#        # VM RAM size (Mb)
#        :memory => 1024, 
#	:net => [
#                 {ip: '192.168.11.151', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dmz-net"},
#                ]
#},
#  :backup => {
#        :hostname => "backup.otus.lab",
#          :box_name => "centos/7",
#        # VM CPU count
#        :cpus => 2,
#        # VM RAM size (Mb)
#        :memory => 1024,
#	:net => [
#                 {ip: '192.168.11.152', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dmz-net"},
#                ]
# },
#   :elkhost => {
#        :hostname => "monlog.otus.lab",
#        :box_name => "centos/7",
#        # VM CPU count
#        :cpus => 2,
#        # VM RAM size (Mb)
#        :memory => 4096, 
#	:net => [
#                 {ip: '192.168.11.153', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dmz-net"},
#                ]
# },
#  :zabbixhost => {
#       :hostname => "zabbixsrv.otus.lab",
#       :box_name => "centos/7",
#       # VM CPU count
#       :cpus => 2,
#       # VM RAM size (Mb)
#       :memory => 2048,
#	:net => [
#                 {ip: '192.168.11.154', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dmz-net"},
#                ]
#},
   :nginxhost => {
        :hostname => "nginx.otus.lab",
        :box_name => "centos/7",
        # VM CPU count
        :cpus => 2,
        # VM RAM size (Mb)
        :memory => 1024,
	:net => [
                 {ip: '192.168.11.100', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dmz-net"},
                ]
 },
#   :apachehost => {
#        :hostname => "apache.otus.lab",
#        :box_name => "centos/7",
#        # VM CPU count
#        :cpus => 2,
#        # VM RAM size (Mb)
#        :memory => 1024,
#	:net => [
#                 {ip: '192.168.11.101', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dmz-net"},
#                ]
# },
#   :srv1c => {
#        :hostname => "srv1c.otus.lab",
#        :box_name => "centos/7",
#        # VM CPU count
#        :cpus => 2,
#        # VM RAM size (Mb)
#        :memory => 1024,
#	:net => [
#                 {ip: '192.168.11.102', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "dmz-net"},
#                ]
# },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    # Disable synced folder
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxconfig[:hostname]

        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        #box.vm.network "private_network", ip: boxconfig[:ip_addr]
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
	case boxname.to_s
           when "router"
             box.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
	     box.vm.network "forwarded_port", guest: 8080, host: 8080, protocol: "tcp", auto_correct: true
             box.vm.network "forwarded_port", guest: 8443, host: 8443, protocol: "tcp", auto_correct: true
	   when "master"
             box.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh"
           when "slave"
             box.vm.network "forwarded_port", guest: 22, host: 2201, id: "ssh"
           when "backup"
             box.vm.network "forwarded_port", guest: 22, host: 2202, id: "ssh"
           when "elkhost"
             box.vm.network "forwarded_port", guest: 22, host: 2203, id: "ssh"
           when "zabbixhost"
             box.vm.network "forwarded_port", guest: 22, host: 2204, id: "ssh"
           when "nginxhost"
             box.vm.network "forwarded_port", guest: 22, host: 2205, id: "ssh"
	     box.vm.network "forwarded_port", guest: 80, host: 8088, protocol: "tcp", auto_correct: true
           when "apachehost"
             box.vm.network "forwarded_port", guest: 22, host: 2206, id: "ssh"
           when "srv1c"
             box.vm.network "forwarded_port", guest: 22, host: 2207, id: "ssh"
             box.vm.network "forwarded_port", guest: 1540, host: 1540, auto_correct: true
             box.vm.network "forwarded_port", guest: 1541, host: 1541, auto_correct: true
             box.vm.network "forwarded_port", guest: 1560, host: 1560, auto_correct: true
        end
           
        box.vm.provider "virtualbox" do |v|
          # Set VM RAM size and CPU count
          v.memory = boxconfig[:memory]
          v.cpus = boxconfig[:cpus]
        end

        box.vm.provision "shell", inline: <<-SHELL
          timedatectl set-timezone Europe/Moscow
	  mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
#        case boxname.to_s
#          when "backup"
#            box.vm.provision "ansible" do |ansible|
#           ansible.verbose = "vv"
#            ansible.playbook = "provision/playbook.yml"
#            ansible.become = "true"
#            ansible.limit = "all"
#          end
#        end

      end
  end
end

