---
#- hosts: all # part running on all hosts
#  become: true
#  tasks:

- name: First initilization
  hosts: all
  become: yes
  roles:
    - pre_init
  tags:
    - pre_init

#- name: Установка postgres11
#  hosts: master, slave
#  become: yes
#  roles:
#    - postgres_install
#  tags:
#    - pg_install
#
#- name: Настройка master
#  hosts: master
#  become: yes
#  roles:
#    - master-setup
#    
#- name: Настройка slave
#  hosts: slave
#  become: yes
#  roles:
#    - slave-setup
#
#- name: Создание тестовой БД
#  hosts: master
#  become: yes
#  roles:
#    - create_test_db
#  tags:
#    - create_db
#
#- name: Настройка barman
#  hosts: backup
#  become: yes
#  roles:
#    - barman_install
#  tags:
#    - backup
#
#- name: Установка 1c 
#  hosts: srv1c, apachehost
#  become: yes
#  roles:
#    - 1cv83_install
#  tags:
#    - 1c_install
#
#- name: Настройка 1c сервера
#  hosts: srv1c
#  become: yes
#  roles:
#    - srv1cv83_setup
#  tags:
#    - 1c_setup
#
#- name: Установка apache2
#  hosts: apachehost
#  become: yes
#  roles:
#    - apache_setup
#  tags:
#    - apache

- name: Установка nginx
  hosts: nginxhost
  become: yes
  roles:
    - nginx_setup
  tags:
    - nginx

- name: Router setup
  hosts: router
  become: yes
  roles:
    - router_setup
  tags:
    - router

      #- name: Configure Prometheus + Node Exporter + Grafana
      #hosts: monlog
      #become: yes
      #roles:
    #    - base_config
    #    - cloudalchemy.prometheus
    #- cloudalchemy.node-exporter
    #- cloudalchemy.grafana
      #vars:
      #prometheus_targets:
      #node:
      #- targets: 
      #    "{{ targets }}"
      #  labels:
      #    env: otusproject
      #tags:
      #- prometheus_install

      #- name: Установка cloudalchemy.node-exporter
      #hosts: master, slave, backup, monlog
      #become: yes
      #roles:
      #- cloudalchemy.node-exporter
      #tags:
      #- nodeexporter

