---
- hosts: all # part running on all hosts
  become: true
  tasks:

  - name: Install epel-release # переведём синтаксис yum из deprecated
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - epel-release
  pre_tasks:
  - name: Modify /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: |
        {{ master_ip }}	{{ master_hostname }}.{{ lab_domain_name }}	{{ master_hostname }}
        {{ slave_ip }}  {{ slave_hostname }}.{{ lab_domain_name }}	{{ slave_hostname }}
        {{ backup_ip }}	{{ backup_hostname }}.{{ lab_domain_name }}	{{ backup_hostname }}
        {{ monlog_ip }}	{{ monlog_hostname }}.{{ lab_domain_name }}	{{ monlog_hostname }}
      state: present

- name: Установка postgres11
  hosts: master, slave, backup
  become: yes
  roles:
    - postgres_install

- name: Настройка master
  hosts: master
  become: yes
  roles:
    - master-setup
    
- name: Настройка slave
  hosts: slave
  become: yes
  roles:
    - slave-setup

- name: Создание тестовой БД
  hosts: master
  become: yes
  roles:
    - create_test_db

- name: Настройка barman
  hosts: backup
  become: yes
  roles:
    - barman_install
  tags:
    - barman

- name: Configure Prometheus + Node Exporter + Grafana
  hosts: monlog
  become: yes
  roles:
    #    - base_config
    - cloudalchemy.prometheus
    - cloudalchemy.node-exporter
    - cloudalchemy.grafana
  vars:
    prometheus_targets:
      node:
      - targets:
        - "{{ monlog_hostname }}:9100"
        - "{{ master_hostname }}:9100"
        - "{{ slave_hostname }}:9100"
        - "{{ backup_hostname }}:9100"
        labels:
          env: otusproject

- name: Установка cloudalchemy.node-exporter
  hosts: master, slave, backup, monlog
  become: yes
  roles:
    - cloudalchemy.node-exporter
  tags:
    - nodeexporter

