# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :r1 => {
        :box_name => "centos/7",
        # VM CPU count
        :cpus => 1,
        # VM RAM size (Mb)
        :memory => 256,
        :net => [
                   {ip: '172.16.1.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "link1"},
                   {ip: '172.16.2.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "link2"}
                ]

  },
  :r2 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.151',
        # VM CPU count
        :cpus => 1,
        # VM RAM size (Mb)
        :memory => 256,
        :net => [
                   {ip: '172.16.1.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "link1"},
                   {ip: '172.16.3.2', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "link3"}
                ]

},
  :r3 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.152',
        # VM CPU count
        :cpus => 1,
        # VM RAM size (Mb)
        :memory => 256,
        :net => [
                   {ip: '172.16.2.3', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "link2"},
                   {ip: '172.16.3.3', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "link3"}
                ]

 },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    # Disable synced folder
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end

        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provider "virtualbox" do |v|
          # Set VM RAM size and CPU count
          v.memory = boxconfig[:memory]
          v.cpus = boxconfig[:cpus]
        end

        box.vm.provision "shell", inline: <<-SHELL
        	timedatectl set-timezone Europe/Moscow
		      mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
#        case boxname.to_s
#          when "r3"
#            box.vm.provision "ansible" do |ansible|
#           ansible.verbose = "vv"
#            ansible.playbook = "provision/playbook.yml"
#            ansible.become = "true"
#            ansible.limit = "all"
#          end
#        end

      end
  end
end

