# Describe VMs
MACHINES = {
  # VM name "kernel update"
  :"kernel-build" => {
              # VM box
              :box_name => "centos-7-9",
              # VM CPU count
              :cpus => 2,
              # VM RAM size (Mb)
              :memory => 1024,
              # networks
              :net => [],
              # forwarded ports
              :forwarded_port => []
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Disable synced folder
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # Apply VM config
    config.vm.define boxname do |box|
      # Set VM base box and hostname
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      # Additional network config if present
      if boxconfig.key?(:net)
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
      end
      # Port-forward config if present
      if boxconfig.key?(:forwarded_port)
        boxconfig[:forwarded_port].each do |port|
          box.vm.network "forwarded_port", port
        end
      end
      # VM resources config
      box.vm.provider "virtualbox" do |v|
        # Set VM RAM size and CPU count
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        #yum install -y mdadm smartmontools hdparm gdisk wget
        #yum install -y http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
        #yum --enablerepo elrepo-kernel install kernel-ml -y
        #grub2-mkconfig -o /boot/grub2/grub.cfg
        #grub2-set-default 0        
      SHELL
      # Reboot vm after up or provision      
      #box.trigger.after [:up, :provision] do |t|
        #t.name = "Reboot after up or provision"
        #t.run_remote = { :inline => "reboot" }
      #end
    end  
  end
end
