---
# tasks file for provision/create_test_db
#- name: Install unzip
#  yum:
#    name: unzip
#    state: present
  
#- name: Remove demo database if exists
#  postgresql_db:
#    name: demo
#    state: absent
#  become: yes
#  become_user: postgres

- name: Get demo database
  unarchive:
    src: "{{ archive_url }}/1CDocDemo.zip"
    dest: /var/tmp/
    remote_src: "{{ remote_src_state }}"

- name: Load demo database
  become: yes 
  become_user: postgres
  shell: psql -f /var/tmp/1CDocDemo.sql
