---
# tasks file for provision/pre_init

- name: RU localedef
  shell: localedef -i ru_RU -f UTF-8 ru_RU.UTF-8

- name: Install epel-release # переведём синтаксис yum из deprecated
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - epel-release

- name: Install requied packages 
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ packages }}"

- name: Modify /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: '{{ item.node_ip }} {{ item.node }}.{{ item.domain }} {{ item.node }}'
  with_items:
    - "{{ nodes }}"
  tags:
    - etc_hosts_modifiy

- name: Start FirewallD
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Set sysctl parameters
  sysctl:
    name: '{{ item.parameter }}'
    value: '{{ item.value}} '
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - '{{ sysctl_params }}'
