---
# tasks file for provision/router_setup


- name: Get UUID for externalinterface
  shell: nmcli c show | grep eth0 | awk '{ print $3 }'
  register: external_uuid

- name: Get UUID for internal interface
  shell: nmcli c show | grep eth1 | awk '{ print $3 }'
  register: internal_uuid

- name: Change zones
  shell: | 
    nmcli c mod {{ internal_uuid.stdout }} connection.zone dmz
    nmcli c mod {{ external_uuid.stdout }} connection.zone external

- name: Permit traffic in default zone for http service
  firewalld:
    zone: dmz
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: Permit traffic in default zone for https service
  firewalld:
    zone: dmz
    service: https
    permanent: yes
    state: enabled
    immediate: yes

- name: Enable remote connections to port 8080 by firewalld
  firewalld:
    zone: external
    port: 8080/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Forward ports to nginx
  shell: |
    firewall-cmd --permanent --zone=external --add-forward-port=port=8080:proto=tcp:toport=80:toaddr={{ nginx_host_ip }}
    firewall-cmd --permanent --zone=external --add-forward-port=port=8443:proto=tcp:toport=443:toaddr={{ nginx_host_ip }}

- name: Enable masquerade to zone dmz
  firewalld:
    zone: dmz
    masquerade: enabled
    permanent: yes
    state: enabled
    immediate: yes

    #    firewall-cmd --zone=dmz --add-masquerade --permanent
    #firewall-cmd --reload
