---
# tasks file for provision/roles/inetrouter-role
- name: Set ip forwarding on in /proc and in the sysctl file and reload if necessary
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Configure internal static route
  shell: "nmcli connection modify System\\ {{ item.int }} +ipv4.routes \"{{ item.route }}\" && nmcli connection up System\\ {{ item.int }}"
  with_items:
    - { int: 'eth1', route: '{{ internal_net }} 192.168.255.2'}

- name: Setup NAT 
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: eth0
    destination: "!{{ internal_net }}"
    jump: MASQUERADE
