---
# tasks file for provision/router-role
- name: Copy chrony.conf
  copy:
    src: files/chrony.conf
    dest: /etc/
    owner: root
    group: root
    mode: 0644
      #when: inventory_hostname == "r1"
  notify: restart_chrony

- name: Set sysctl parameters
  sysctl:
    name: '{{ item.parameter }}'
    value: '{{ item.value}} '
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - '{{ sysctl_params }}'

- name: Setup loopback sub interface
  template:
    src: ifcfg-lo.2.j2
    dest: '/etc/sysconfig/network-scripts/ifcfg-lo.2'
    owner: root
    group: root
    mode: 0644
  notify: restart_Network

- name: Remove default from eth0
  shell: nmcli connection modify System\ eth0 ipv4.never-default yes && nmcli connection up System\ eth0
  when: inventory_hostname != "r1"

- name: Create ospfd.conf
  template:
    src: ospfd.conf.j2
    dest: '/etc/quagga/ospfd.conf'
    owner: quagga
    group: quaggavt
    mode: 0664
  notify: start_quagga

- name: Allow zebra to write config
  seboolean:
    name: zebra_write_config
    state: yes
    persistent: yes
