---
# tasks file for provision/router-role
- name: Copy chrony.conf
  copy:
    src: files/chrony.conf
    dest: /etc/
    owner: root
    group: root
    mode: 0644
      #when: inventory_hostname == "r1"
  notify: restart_chrony

- name: Set sysctl parameters
  sysctl:
    name: '{{ item.parameter }}'
    value: '{{ item.value}} '
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - '{{ sysctl_params }}'

- name: Setup loopback sub interface
  template:
    src: ifcfg-lo.2.j2
    dest: '/etc/sysconfig/network-scripts/ifcfg-lo.2'
    owner: root
    group: root
    mode: 0644
  notify: restart_Network

- name: Remove default from eth0
  shell: nmcli connection modify System\ eth0 ipv4.never-default yes && nmcli connection up System\ eth0
  when: inventory_hostname != "r1"


- name: Enable services
  systemd:
    state: '{{ item.state }}'
    name: '{{ item.name }}'
    enabled: '{{ item.enabled }}'
    daemon_reload: yes
  with_items:
    - '{{ quagga_services }}' 
