---
# tasks file for provision/router-role
- name: Copy chrony.conf
  copy:
    src: files/chrony.conf
    dest: /etc/
    owner: root
    group: root
    mode: 0644
      #when: inventory_hostname == "r1"
  notify: restart_chrony

- name: Set sysctl parameters
  sysctl:
    name: '{{ item.parameter }}'
    value: '{{ item.value}} '
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - '{{ sysctl_params }}'

