---
packages:
    - quagga
    - tcpdump
    - libsemanage-python

sysctl_params:
  - parameter: net.ipv4.ip_forward
    value: '1'
  - parameter: net.ipv4.conf.all.forwarding
    value: '1'
  - parameter: net.ipv4.conf.all.rp_filter
    value: '2'

quagga_services:
  - name: zebra
    state: started
    enabled: yes
  - name: ospfd
    state: started
    enabled: yes
