---
# tasks file for provision/postgres_install


  #- name: Install PostgreSQL repo
  #yum:
  #  name: "{{ postgresql_repo }}"
  #  state: present

- name: Install centos.rpm from PostgresPro
  yum:
    name: "{{ postgrespro_repo }}"
    update_cache: yes

- name: Install PostgreSQL packages
  package:
    name: "{{ packages }}"
    state: present
