---
# tasks file for provision/postgres_install
- name: Install PostgreSQL repo
  yum:
    name: "{{ postgresql_repo }}"
    state: present

- name: Install PostgreSQL packages
  package:
    name: "{{ packages }}"
    state: present
