---
# tasks file for provision/postgres_install

- name: RU localedef
  shell: localedef -i ru_RU -f UTF-8 ru_RU.UTF-8

  #- name: Install PostgreSQL repo
  #yum:
  #  name: "{{ postgresql_repo }}"
  #  state: present

- name: Install centos.rpm from PostgresPro
  yum:
    name: "{{ postgrespro_repo }}"
    update_cache: yes

- name: Install PostgreSQL packages
  package:
    name: "{{ packages }}"
    state: present
